# Generated by Django 5.2.17 on 2026-08-09 05:36

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('allowed_email_domains', models.JSONField(default=list, help_text='Allowed email domains, e.g. ["gim.ac.in", "student.gim.ac.in"].')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostels', to='laundry.institute')),
            ],
            options={
                'ordering': ('institute', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to='laundry.institute')),
            ],
            options={
                'verbose_name': 'administrator',
                'verbose_name_plural': 'administrators',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='InstituteRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quota_limit', models.PositiveIntegerField(default=3, help_text='Max washer bookings counted against quota in the rolling window.')),
                ('quota_window_days', models.PositiveIntegerField(default=7)),
                ('cooldown_hours', models.PositiveIntegerField(default=6, help_text='Minimum hours after a washer slot ends before the next washer booking.')),
                ('advance_window_days', models.PositiveIntegerField(default=7, help_text='How many days ahead a student may book.')),
                ('cancellation_cutoff_hours', models.PositiveIntegerField(default=6, help_text='Cancelling later than this many hours before start still counts against quota.')),
                ('dryer_cap_enabled', models.BooleanField(default=False, help_text='If enabled, dryer bookings consume washer quota and trigger cooldown.')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='laundry.institute')),
            ],
            options={
                'verbose_name': 'institute rule',
                'verbose_name_plural': 'institute rules',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('washer', 'Washer'), ('dryer', 'Dryer')], max_length=16)),
                ('location_name', models.CharField(help_text='Human-readable location, e.g. "3rd Floor · A Wing".', max_length=200)),
                ('operating_window_start', models.TimeField(default=datetime.time(0, 0), help_text='Inclusive. Equal to end means 24-hour operation.')),
                ('operating_window_end', models.TimeField(default=datetime.time(0, 0), help_text='Exclusive upper bound of the operating window.')),
                ('slot_length_minutes', models.PositiveIntegerField(default=60)),
                ('is_offline', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='laundry.hostel')),
            ],
            options={
                'ordering': ('hostel', 'kind', 'location_name'),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('counts_against_quota', models.BooleanField(default=True)),
                ('is_late_cancel', models.BooleanField(default=False, help_text='True when cancelled inside the institute cutoff; still counts against quota.')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='laundry.machine')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp_opt_in', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Assigned by an administrator, not chosen by the student.', max_length=16)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_ends', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('home_hostel', models.ForeignKey(blank=True, help_text='Assigned by an administrator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='laundry.hostel')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='laundry.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booking_confirmed', models.BooleanField(default=True)),
                ('slot_reminder', models.BooleanField(default=True)),
                ('booking_cancelled_offline', models.BooleanField(default=True)),
                ('exchange_request', models.BooleanField(default=True)),
                ('exchange_outcome', models.BooleanField(default=True)),
                ('ticket_update', models.BooleanField(default=True)),
                ('strike', models.BooleanField(default=True)),
                ('suspension', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='laundry.student')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('slot_reminder', 'Upcoming slot reminder'), ('booking_cancelled_offline', 'Booking cancelled (machine offline)'), ('exchange_request', 'Exchange request'), ('exchange_outcome', 'Exchange outcome'), ('ticket_update', 'Ticket update'), ('strike', 'Strike'), ('suspension', 'Suspension')], max_length=40)),
                ('kind', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Optional target type: booking, exchange, ticket, strike.', max_length=40)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='laundry.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('request', 'Request'), ('swap', 'Swap')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Why an approved exchange failed rule checks.')),
                ('offered_booking', models.ForeignKey(blank=True, help_text='Set when kind is swap.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_offer', to='laundry.booking')),
                ('target_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_target', to='laundry.booking')),
                ('holder', models.ForeignKey(help_text='Current holder of the target booking (denormalized for queries).', on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_received', to='laundry.student')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_sent', to='laundry.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='laundry.student'),
        ),
        migrations.CreateModel(
            name='AvailabilityMiss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(help_text='Hour of day in 0–23 (institute-local; stored as requested).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_misses', to='laundry.machine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_misses', to='laundry.student')),
            ],
            options={
                'verbose_name': 'availability miss',
                'verbose_name_plural': 'availability misses',
                'ordering': ('-date', '-hour'),
            },
        ),
        migrations.CreateModel(
            name='SuperAdministrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadministrator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'super administrator',
                'verbose_name_plural': 'super administrators',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('conflict', 'Conflict'), ('maintenance', 'Maintenance')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('number', models.PositiveIntegerField(blank=True, help_text='Display number (e.g. 427 → #427). Assigned by services.', null=True, unique=True)),
                ('slot_start', models.DateTimeField(blank=True, help_text='Conflict tickets: slot start attached at raise time.', null=True)),
                ('student_note', models.TextField(blank=True)),
                ('committee_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text="Conflict tickets: the student's booking for that slot.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='laundry.booking')),
                ('machine', models.ForeignKey(help_text='Auto-attached for conflict and maintenance tickets.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='laundry.machine')),
                ('recorded_holder', models.ForeignKey(blank=True, help_text='Conflict tickets: holder recorded at raise time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_recorded_holder', to='laundry.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='laundry.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('date', models.DateField()),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strikes_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strikes', to='laundry.student')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strikes', to='laundry.ticket')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='laundry.ticket')),
            ],
            options={
                'ordering': ('occurred_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='hostel',
            constraint=models.UniqueConstraint(fields=('institute', 'name'), name='uniq_hostel_name_per_institute'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', '-created_at'], name='laundry_not_student_e8bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['holder', 'status'], name='laundry_exc_holder__dc5980_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['requester', 'status'], name='laundry_exc_request_40da8c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['machine', 'starts_at'], name='laundry_boo_machine_c49e40_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'starts_at'], name='laundry_boo_student_31aa03_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True), ('is_active', True)), fields=('machine', 'starts_at'), name='uniq_active_booking_machine_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilitymiss',
            constraint=models.UniqueConstraint(fields=('student', 'machine', 'date', 'hour'), name='uniq_availability_miss_student_slot'),
        ),
        migrations.AddConstraint(
            model_name='availabilitymiss',
            constraint=models.CheckConstraint(condition=models.Q(('hour__gte', 0), ('hour__lte', 23)), name='availabilitymiss_hour_0_23'),
        ),
    ]
