# Generated by Django 5.2.17 on 2026-08-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_ticket_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='channel',
            field=models.CharField(choices=[('app', 'App'), ('android', 'Android app'), ('ios', 'iOS app'), ('whatsapp', 'WhatsApp'), ('website', 'Website')], default='app', help_text='Booking source channel; default "app" until multi-channel clients exist.', max_length=32),
        ),
    ]
