# Generated by Django 6.1 on 2026-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_booking_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='channel',
            field=models.CharField(choices=[('app', 'App'), ('android', 'Android app'), ('ios', 'iOS app'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('mcp', 'Assistant (MCP)')], default='app', help_text='Booking source channel; default "app" until multi-channel clients exist.', max_length=32),
        ),
    ]
