# Generated by Django 6.1 on 2026-08-20 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_alter_booking_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actor_label', models.CharField(help_text='Who acted, as they were named at the time.', max_length=200)),
                ('action', models.CharField(choices=[('machine.offline', 'Machine taken offline'), ('machine.online', 'Machine brought online'), ('machine.hours', 'Machine hours changed'), ('machine.created', 'Machine added'), ('machine.updated', 'Machine updated'), ('hostel.created', 'Hostel added'), ('hostel.updated', 'Hostel updated'), ('rules.updated', 'Booking rules changed'), ('student.created', 'Student added'), ('student.assigned', 'Student hostel/gender changed'), ('student.disabled', 'Student account disabled'), ('student.enabled', 'Student account re-enabled'), ('student.promoted', 'Student promoted to administrator'), ('student.reset_sent', 'Password reset link sent'), ('student.imported', 'Students imported'), ('strike.recorded', 'Strike recorded'), ('strike.revoked', 'Strike revoked'), ('suspension.added', 'Student suspended'), ('suspension.lifted', 'Suspension lifted'), ('ticket.resolved', 'Ticket resolved'), ('ticket.updated', 'Ticket updated'), ('booking.cancelled', 'Booking cancelled by admin')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, help_text='What was acted on, as it was named at the time.', max_length=200)),
                ('summary', models.CharField(max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='laundry.administrator')),
                ('institute', models.ForeignKey(blank=True, help_text='Null for super-administrator actions spanning institutes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='laundry.institute')),
            ],
            options={
                'verbose_name': 'admin audit entry',
                'verbose_name_plural': 'admin audit log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['institute', '-created_at'], name='laundry_adm_institu_889e5e_idx'), models.Index(fields=['actor', '-created_at'], name='laundry_adm_actor_i_2486bf_idx')],
            },
        ),
    ]
