# Generated by Django 6.1 on 2026-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0005_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('machine.offline', 'Machine taken offline'), ('machine.online', 'Machine brought online'), ('machine.hours', 'Machine hours changed'), ('machine.created', 'Machine added'), ('machine.updated', 'Machine updated'), ('hostel.created', 'Hostel added'), ('hostel.updated', 'Hostel updated'), ('rules.updated', 'Booking rules changed'), ('student.created', 'Student added'), ('student.assigned', 'Student hostel/gender changed'), ('student.disabled', 'Student account disabled'), ('student.enabled', 'Student account re-enabled'), ('student.promoted', 'Student promoted to administrator'), ('student.reset_sent', 'Password reset link sent'), ('student.imported', 'Students imported'), ('strike.recorded', 'Strike recorded'), ('strike.revoked', 'Strike revoked'), ('suspension.added', 'Student suspended'), ('suspension.lifted', 'Suspension lifted'), ('ticket.resolved', 'Ticket resolved'), ('ticket.updated', 'Ticket updated'), ('booking.cancelled', 'Booking cancelled by admin'), ('admin.password_changed', 'Administrator changed own password')], db_index=True, max_length=40),
        ),
    ]
