# Generated by Django 6.0 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundry", "0007_exchange_reject_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="floor",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Home floor in the hostel, e.g. "3rd Floor".',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="home_hostel",
            field=models.ForeignKey(
                blank=True,
                help_text="Chosen at sign-up, or assigned by an administrator.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="laundry.hostel",
            ),
        ),
    ]
