# Generated by Django 6.1 on 2026-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0011_convert_conflict_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituterule',
            name='quota_limit',
            field=models.PositiveIntegerField(default=3, help_text='Max washer bookings counted against quota Monday to Sunday.'),
        ),
        migrations.AlterField(
            model_name='instituterule',
            name='quota_window_days',
            field=models.PositiveIntegerField(default=7, help_text='Kept for API compatibility. Quota is always a Monday–Sunday week.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Unused. Kept for older rows; new tickets do not attach a booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='laundry.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='machine',
            field=models.ForeignKey(help_text='The machine this report is about.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='laundry.machine'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recorded_holder',
            field=models.ForeignKey(blank=True, help_text='Unused. Kept for older rows; new tickets do not attach a holder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_recorded_holder', to='laundry.student'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='slot_start',
            field=models.DateTimeField(blank=True, help_text='Unused. Kept for older rows; new tickets do not attach a slot.', null=True),
        ),
    ]
