# Generated by Django 6.1 on 2026-08-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0012_alter_ticket_and_quota_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='gender',
        ),
        migrations.AlterField(
            model_name='student',
            name='floor',
            field=models.CharField(blank=True, default='', help_text='Unused. Machines belong to a hostel, not to a student.', max_length=64),
        ),
    ]
