# Generated by Django 6.1 on 2026-08-17 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundry', '0003_booking_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="What this token is for, e.g. 'Claude desktop'.", max_length=100)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hint', models.CharField(help_text='Leading characters, shown so a student can tell tokens apart.', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to='laundry.student')),
            ],
            options={
                'verbose_name': 'MCP token',
                'verbose_name_plural': 'MCP tokens',
                'ordering': ('-created_at',),
            },
        ),
    ]
