# Generated by Django 6.1 on 2026-08-17 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_alter_booking_channel'),
        ('mcp_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('redirect_uris', models.JSONField(default=list)),
                ('client_uri', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'OAuth client',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=128)),
                ('scope', models.CharField(default='laundry.book', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_codes', to='laundry.student')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='mcp_server.oauthclient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='mcptoken',
            name='oauth_client',
            field=models.ForeignKey(blank=True, help_text='Set when this token came from the OAuth flow rather than being pasted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='mcp_server.oauthclient'),
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scope', models.CharField(default='laundry.book', max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='mcp_server.oauthclient')),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='mcp_server.oauthrefreshtoken')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to='laundry.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
